version: "3"
services:
  www:
    image: php:8.1-apache-buster
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
